import numpy as np
A = np.array([[1,2],[3,4],[5,6]])
print(A)
U,S,V = np.linalg.svd(A)
print("Left Singular Matrix")
print(U)
print("Singular Matrix")
print(S)
print("Right Singular Matrix")
print(V)
Sigma=np.zeros((A.shape[0],A.shape[1]))
np.fill_diagonal(Sigma,S)
B=U.dot(Sigma.dot(V))
print("Reconstructed Matrix:\n",B)