import numpy as np
matrix=np.random.randint(10,size=(2,2))
print("Random generated matrix")
print(matrix)
det=np.linalg.det(matrix)
print("Determinant of matrix:",det)
inverse=np.linalg.inv(matrix)
print("Inverse of matrix:\n",inverse)
rank=np.linalg.matrix_rank(matrix)
print("Rank of matrix:\n",rank)
Eval,EVector=np.linalg.eig(matrix)
print("Eigenvalues of matrix:\n",Eval)
print("Eigenvectors of matrix:\n",EVector)
array_1D=matrix.flatten()
print("Array 1D of matrix:\n",array_1D)
